export const routes = {
  public: {
    home: "/",
    buy: "/buy",
    rent: "/rent",
    property: (propertyId: string) => `/property/${propertyId}`,
    area: (slug: string) => `/area/${slug}`,
    agencies: "/agencies",
    agency: (agencySlug: string) => `/agencies/${agencySlug}`,
    agent: (agentSlug: string) => `/agents/${agentSlug}`,
    valuator: (valuatorSlug: string) => `/valuators/${valuatorSlug}`,
  },
  auth: {
    login: "/login",
    signup: "/signup",
  },
  onboarding: {
    advertise: "/advertise",
    assess: "/assess",
    agentApplicationNew: "/agent/applications/new",
    agentApplication: (applicationId: string) => `/agent/applications/${applicationId}`,
    agencyRegistrationNew: "/agency/registration-requests/new",
    agencyRegistration: (requestId: string) => `/agency/registration-requests/${requestId}`,
    valuatorApplicationNew: "/valuator/applications/new",
    valuatorApplication: (applicationId: string) => `/valuator/applications/${applicationId}`,
  },
  app: {
    account: "/account",
    saved: "/saved",
    portal: "/portal",
    portalListings: "/portal/listings",
    portalValuations: "/portal/valuations",
    portalAgency: "/portal/agency",
    portalAgents: "/portal/agents",
    portalProfile: "/portal/profile",
    portalSettings: "/portal/settings",
  },
  admin: {
    home: "/admin/dashboard",
    dashboard: "/admin/dashboard",
    agencies: "/admin/agencies",
    agents: "/admin/agents",
    valuators: "/admin/valuators",
    valuations: "/admin/valuations",
    properties: "/admin/properties",
    listings: "/admin/listings",
  },
} as const;
