export const routes = {
  public: {
    home: "/",
    buy: "/buy",
    rent: "/rent",
    property: (propertyId: string) => `/property/${propertyId}`,
    area: (slug: string) => `/area/${slug}`,
    agencies: "/agencies",
    agency: (agencySlug: string) => `/agencies/${agencySlug}`,
    agent: (agentSlug: string) => `/agents/${agentSlug}`,
    valuator: (valuatorSlug: string) => `/valuators/${valuatorSlug}`,
  },
  auth: {
    login: "/login",
    signup: "/signup",
  },
  onboarding: {
    agent: "/agent",
    agentStatus: "/agent/status",
    agency: "/agency",
    agencyStatus: "/agency/status",
    valuator: "/valuator",
    valuatorStatus: "/valuator/status",
  },
  app: {
    account: "/account",
    saved: "/saved",
    portal: "/portal",
    portalListings: "/portal/listings",
    portalValuations: "/portal/valuations",
    portalAgency: "/portal/agency",
    portalAgents: "/portal/agents",
    portalProfile: "/portal/profile",
    portalSettings: "/portal/settings",
  },
  admin: {
    home: "/admin",
    agencies: "/admin/agencies",
    agents: "/admin/agents",
    valuators: "/admin/valuators",
    valuations: "/admin/valuations",
    properties: "/admin/properties",
    listings: "/admin/listings",
  },
} as const;
